// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PokeAPI.Data;

#nullable disable

namespace PokeAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.24");

            modelBuilder.Entity("PokeAPI.Domain.Entities.Pokemon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ColorGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Especie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ColorGroupId");

                    b.ToTable("Pokemon");
                });

            modelBuilder.Entity("PokeAPI.Domain.Entities.PokemonColorGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Color")
                        .IsUnique();

                    b.ToTable("PokemonColorGroup");
                });

            modelBuilder.Entity("PokeAPI.Domain.Entities.Pokemon", b =>
                {
                    b.HasOne("PokeAPI.Domain.Entities.PokemonColorGroup", "ColorGroup")
                        .WithMany("Pokemons")
                        .HasForeignKey("ColorGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ColorGroup");
                });

            modelBuilder.Entity("PokeAPI.Domain.Entities.PokemonColorGroup", b =>
                {
                    b.Navigation("Pokemons");
                });
#pragma warning restore 612, 618
        }
    }
}
